---
name: Lume CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check types
        run: deno check

      # Delete if uncomfortable
      - name: Check format
        run: deno fmt --check
...
